name: KEITI 공지사항 메일링

on:
  schedule:
    - cron: '0 15 * * *'  # 매일 00:00 KST → UTC 기준 15시
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 패키지 설치
        run: pip install requests beautifulsoup4

      - name: 스크립트 실행
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python keiti_notice_mailer.py
